name: Build & Deploy Main Site + Lighthouse

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        npm ci

    - name: Install Lighthouse CI
      run: npm install -g @lhci/cli

    - name: Run Lighthouse CI
      run: |
        lhci autorun
        node generate-lhci-index.js

    - name: Prepare Combined Deploy Folder
      run: |
        mkdir publish
        cp -r ./*.html ./publish/
        cp -r ./css ./publish/ || true
        cp -r ./js ./publish/ || true
        cp -r ./images ./publish/ || true
        cp -r ./assets ./publish/ || true
        mkdir -p ./publish/lighthouse
        cp -r ./lhci-report/index.html ./publish/lighthouse/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
        publish_branch: gh-pages
